// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DSC.Data;

#nullable disable

namespace DSC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220115442_AddUserIdToWorkItem")]
    partial class AddUserIdToWorkItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // This is a placeholder - the actual model is in the snapshot
#pragma warning restore 612, 618
        }
    }
}
